apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fqdn-networkpolicy-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fqdn-networkpolicy-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      {{- include "fqdn-networkpolicy-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fqdn-networkpolicy-operator.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "fqdn-networkpolicy-operator.serviceAccountName" . }}
      terminationGracePeriodSeconds: 10
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
