replicaCount: 1

image:
  repository: ghcr.io/twsouthwick/fqdn-networkpolicy-operator
  pullPolicy: IfNotPresent
  # Overrides the image tag; defaults to the chart appVersion.
  tag: ""

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

nameOverride: ""
fullnameOverride: ""
